export const START_LOADING = "REQUESTS";
export const STOP_LOADING = "STOP_LOADING";
export const SET_COORS = "SET_COORS";
export const SET_CURRENT_WEATHER_INFO = "SET_CURRENT_WEATHER_INFO";
export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const SET_CITY_NAME = "SET_CITY_NAME";
export const SET_IMAGE_URL = "SET_IMAGE_URL";
